schema: ./src/graphql/schema.graphqls
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: ${meta.env.VITE_GRAPHQL_HTTP_URL:-"http://localhost:8080/graphql"}
      headers:
        user-agent: JS GraphQL
      introspect: true
